import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import React from 'react'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	                                   children
                                   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
		<body
			className={'page-container'}
		>
		<div className={'page-wrapper'}>
			<header>
				<Header />
			</header>
			<main className={'main-container'}>
				{children}
			</main>
			<footer className={'footer'}>
				<Footer />
			</footer>
			<div className={'bottom'}>
				<div className={'policyInfo'}>
					<Link href='#'>Политика обработки данных</Link>
					<Link href='#'>Политика конфиденциальности</Link>
				</div>
				<p>© 2022 — 2024 «GETLUXE»</p>
			</div>
		</div>
		</body>
		</html>
	)
}
